services:
  - type: web
    name: landing-blazek
    runtime: static
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
